### ISSUE TITLE
Mesh quality of unseen body parts

### ISSUE THREAD

**Issue by MinJunKang** [snuvclab/gala#2]
Hello, thanks for sharing great work!
I have several questions about this work.

1. I found that GALA only uses rendering loss for reconstruction loss. Why do we not use the chamfer loss together since we have the ground-truth posed mesh?

2. I ran GALA to decompose the upper cloth of one of the clothed humans in the THuman 2 dataset. I found that the mesh of the decomposed inner body contains so much noise. Is it expected result to contain so much noise in unseen body mesh since this is only guided by SDS loss? I also realized that there are only rendering results for decomposed human and cloth parts in the paper. If this is expected, can we better improve the unseen body mesh? (please refer to attached result)

![그림1](https://github.com/snuvclab/gala/assets/29685163/7c783de4-74fd-441f-a9d6-aef7ca893668)

Again, thanks for sharing the code.

**Comment by taeksuu** [comment]
Hi, 

1. We found that rendering-based loss is enough for reconstruction and in fact much better at reconstructing detailed surfaces than 3d losses.

2. We noticed those noisy surfaces when renderings for SDS loss were not zoomed in enough. Since we set the zoom-in parameters based on the b-box of separated clothing, the zoom-ins could be insufficient for cases such as long-sleeved shirts. You may try increasing the maximum value of the zoom-in parameters manually or increase the iterations for better outputs.

Thank you
